repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo format
        entry: cargo fmt --all -- --check
        language: rust
        pass_filenames: false
        
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy -- -D warnings
        language: rust
        pass_filenames: false
        
      - id: cargo-test
        name: Cargo test
        entry: cargo test
        language: rust
        pass_filenames: false
        
      - id: cargo-doc
        name: Cargo doc
        entry: cargo doc --no-deps --document-private-items
        language: rust
        pass_filenames: false
        
      - id: example-tests
        name: Example tests
        entry: ./scripts/run_examples.sh
        language: script
        pass_filenames: false
